name: SectorOS_RE2 Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: make -f src/Makefile install_prereqs
    - name: make all
      run: make -f src/Makefile all PREFIX="$HOME/build-i686" GRUBDIR=/usr/bin
    - name: upload_artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          *.iso
          *.elf