name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: | 
        mkdir -p /tmp/i686-elf-tools
        pushd /tmp/i686-elf-tools
        wget https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
        unzip i686-elf-tools-linux.zip
        rm i686-elf-tools-linux.zip
    - name: make all
      run: make -f src/Makefile all PREFIX=/tmp/i686-elf-tools/ GRUBDIR=/usr/bin/
    - name: upload_artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          *.iso
          *.elf

